// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

//go:build ebpf && linux

package ebpftest

import (
	"bytes"
	"encoding/binary"
	"errors"
	"net"
	"os"
	"testing"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/stretchr/testify/require"
	"golang.org/x/sys/unix"
)

// RequirePrivileged skips the test if the current process lacks BPF privileges.
// It checks for CAP_BPF or CAP_SYS_ADMIN in the effective capability set.
func RequirePrivileged(t *testing.T) {
	t.Helper()

	if os.Geteuid() == 0 {
		return // root has all capabilities
	}

	var hdr unix.CapUserHeader
	var data [2]unix.CapUserData
	hdr.Version = unix.LINUX_CAPABILITY_VERSION_3

	if err := unix.Capget(&hdr, &data[0]); err != nil {
		t.Skipf("skipping eBPF test: cannot query capabilities: %v", err)
		return
	}

	if !hasEffectiveCap(data, unix.CAP_BPF) && !hasEffectiveCap(data, unix.CAP_SYS_ADMIN) {
		t.Skip("skipping eBPF test: need CAP_BPF or CAP_SYS_ADMIN")
	}
}

// hasEffectiveCap checks whether the given capability is set in the effective set.
func hasEffectiveCap(data [2]unix.CapUserData, cap uintptr) bool {
	i := cap / 32
	bit := uint32(1) << (cap % 32)
	return data[i].Effective&bit != 0
}

// RemoveMapPinning sets Pinning to PinNone on all maps in the collection spec.
// This is required because embedded objects may have LIBBPF_PIN_BY_NAME which
// would fail in test environments without /sys/fs/bpf access.
func RemoveMapPinning(spec *ebpf.CollectionSpec) {
	for _, m := range spec.Maps {
		m.Pinning = ebpf.PinNone
	}
}

// ReadPerfEvent reads one perf record from the reader within the given timeout,
// decodes it into T using binary.Read (little-endian), and returns it.
// Returns (zero, false) if the deadline expires without an event.
func ReadPerfEvent[T any](t *testing.T, reader *perf.Reader, timeout time.Duration) (T, bool) {
	t.Helper()

	reader.SetDeadline(time.Now().Add(timeout))

	record, err := reader.Read()
	var zero T
	if errors.Is(err, os.ErrDeadlineExceeded) {
		return zero, false
	}
	require.NoError(t, err)
	require.Zero(t, record.LostSamples, "perf reader lost samples")

	var event T
	err = binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &event)
	require.NoError(t, err, "failed to decode perf event")

	return event, true
}

// AssertNoPerfEvent asserts that no perf event is emitted within the given timeout.
func AssertNoPerfEvent(t *testing.T, reader *perf.Reader, timeout time.Duration) {
	t.Helper()

	reader.SetDeadline(time.Now().Add(timeout))

	_, err := reader.Read()
	if errors.Is(err, os.ErrDeadlineExceeded) {
		return // expected: no event
	}
	if err != nil {
		return // reader error is acceptable for "no event" assertion
	}
	t.Fatal("expected no perf event but got one")
}

// IPToNative converts an IP string to its uint32 representation as stored by
// eBPF programs. Programs store ip->saddr directly from the packet (network
// byte order), which on a LE machine is the raw 4 bytes interpreted as a LE uint32.
func IPToNative(ipStr string) uint32 {
	ip := net.ParseIP(ipStr).To4()
	return *(*uint32)(unsafe.Pointer(&ip[0]))
}

// PortToNetwork converts a host port number to the byte order used by eBPF
// programs. Programs store tcp->source / tcp->dest directly from the packet
// header (big-endian), then perf events are decoded as LE by binary.Read.
func PortToNetwork(port uint16) uint16 {
	var buf [2]byte
	binary.BigEndian.PutUint16(buf[:], port)
	return binary.LittleEndian.Uint16(buf[:])
}

// LPMTrieKey represents the key for the retina_filter LPM trie map.
// This struct matches the layout generated by bpf2go for all plugins
// that use the shared retina_filter map.
type LPMTrieKey struct {
	Prefixlen uint32
	Data      uint32
}

// PopulateFilterMap inserts IPs into a retina_filter LPM trie map so that
// the eBPF program's lookup() function matches them.
func PopulateFilterMap(t *testing.T, filterMap *ebpf.Map, ips ...net.IP) {
	t.Helper()
	for _, ip := range ips {
		ipBytes := ip.To4()
		require.NotNil(t, ipBytes, "expected IPv4 address")

		key := LPMTrieKey{
			Prefixlen: 32,
			Data:      *(*uint32)(unsafe.Pointer(&ipBytes[0])),
		}
		val := uint8(1)
		err := filterMap.Put(key, val)
		require.NoError(t, err)
	}
}

// RunProgram executes an eBPF program via prog.Run() and returns the retval.
// Use this for TC classifier programs where perf events fire during Run().
func RunProgram(t *testing.T, prog *ebpf.Program, pkt []byte) uint32 {
	t.Helper()
	ret, err := prog.Run(&ebpf.RunOptions{
		Data: pkt,
	})
	require.NoError(t, err)
	return ret
}

// RunSocketFilter executes a socket filter program via prog.Test().
//
// BPF_PROG_TEST_RUN for socket filters calls eth_type_trans(), which
// strips the first 14 bytes (Ethernet header) from the packet data.
// This function prepends a 14-byte dummy so the kernel strips that
// instead of the real Ethernet header, keeping bpf_skb_load_bytes
// offsets consistent with production.
//
// Perf events do NOT fire during Test() — use ReadPerCPUMap to read
// results from a per-CPU scratch map instead.
func RunSocketFilter(t *testing.T, prog *ebpf.Program, pkt []byte) uint32 {
	t.Helper()
	padded := append(make([]byte, 14), pkt...)
	ret, _, err := prog.Test(padded)
	require.NoError(t, err)
	return ret
}

// ReadPerCPUMap reads a per-CPU array map at the given key and returns the
// first entry with a non-zero first 8 bytes (typically a timestamp field).
// This is the standard way to read results from BPF programs that use a
// per-CPU scratch map during BPF_PROG_TEST_RUN (where perf events don't fire).
func ReadPerCPUMap[T any](t *testing.T, m *ebpf.Map, key uint32) (T, bool) {
	t.Helper()
	var values []T
	err := m.Lookup(key, &values)
	require.NoError(t, err, "failed to read per-CPU map")

	// Find the CPU that ran the program by looking for a non-zero timestamp
	// (the first 8 bytes of the struct).
	for _, v := range values {
		raw := (*[8]byte)(unsafe.Pointer(&v))
		ts := binary.LittleEndian.Uint64(raw[:])
		if ts != 0 {
			return v, true
		}
	}
	var zero T
	return zero, false
}

// ReadRingBufEvent reads one ringbuf record from the reader within the given timeout,
// decodes it into T using binary.Read (little-endian), and returns it.
// Returns (zero, false) if the deadline expires without an event.
func ReadRingBufEvent[T any](t *testing.T, rb *ringbuf.Reader, timeout time.Duration) (T, bool) {
	t.Helper()

	type result struct {
		rec ringbuf.Record
		err error
	}

	// ringbuf.Read is blocking, so we run it in a goroutine to support timeout.
	// When the test ends or rb is closed, this should unblock.
	ch := make(chan result, 1)
	go func() {
		rec, err := rb.Read()
		ch <- result{rec, err}
	}()

	select {
	case res := <-ch:
		require.NoError(t, res.err)
		var event T
		err := binary.Read(bytes.NewReader(res.rec.RawSample), binary.LittleEndian, &event)
		require.NoError(t, err)
		return event, true
	case <-time.After(timeout):
		// Caller should cleanup reader to stop the goroutine
		return *new(T), false
	}
}
