// Code generated by MockGen. DO NOT EDIT.
// Source: basemetricsobject.go
//
// Generated by this command:
//
//	mockgen -source=basemetricsobject.go -destination=mock_basemetricsobject.go -package=metrics
//

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	log "github.com/microsoft/retina/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockbaseMetricInterface is a mock of baseMetricInterface interface.
type MockbaseMetricInterface struct {
	ctrl     *gomock.Controller
	recorder *MockbaseMetricInterfaceMockRecorder
}

// MockbaseMetricInterfaceMockRecorder is the mock recorder for MockbaseMetricInterface.
type MockbaseMetricInterfaceMockRecorder struct {
	mock *MockbaseMetricInterface
}

// NewMockbaseMetricInterface creates a new mock instance.
func NewMockbaseMetricInterface(ctrl *gomock.Controller) *MockbaseMetricInterface {
	mock := &MockbaseMetricInterface{ctrl: ctrl}
	mock.recorder = &MockbaseMetricInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbaseMetricInterface) EXPECT() *MockbaseMetricInterfaceMockRecorder {
	return m.recorder
}

// additionalLabels mocks base method.
func (m *MockbaseMetricInterface) additionalLabels() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "additionalLabels")
	ret0, _ := ret[0].([]string)
	return ret0
}

// additionalLabels indicates an expected call of additionalLabels.
func (mr *MockbaseMetricInterfaceMockRecorder) additionalLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "additionalLabels", reflect.TypeOf((*MockbaseMetricInterface)(nil).additionalLabels))
}

// clean mocks base method.
func (m *MockbaseMetricInterface) clean() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "clean")
}

// clean indicates an expected call of clean.
func (mr *MockbaseMetricInterfaceMockRecorder) clean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clean", reflect.TypeOf((*MockbaseMetricInterface)(nil).clean))
}

// destinationCtx mocks base method.
func (m *MockbaseMetricInterface) destinationCtx() ContextOptionsInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "destinationCtx")
	ret0, _ := ret[0].(ContextOptionsInterface)
	return ret0
}

// destinationCtx indicates an expected call of destinationCtx.
func (mr *MockbaseMetricInterfaceMockRecorder) destinationCtx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "destinationCtx", reflect.TypeOf((*MockbaseMetricInterface)(nil).destinationCtx))
}

// getLogger mocks base method.
func (m *MockbaseMetricInterface) getLogger() *log.ZapLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getLogger")
	ret0, _ := ret[0].(*log.ZapLogger)
	return ret0
}

// getLogger indicates an expected call of getLogger.
func (mr *MockbaseMetricInterfaceMockRecorder) getLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getLogger", reflect.TypeOf((*MockbaseMetricInterface)(nil).getLogger))
}

// isAdvanced mocks base method.
func (m *MockbaseMetricInterface) isAdvanced() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isAdvanced")
	ret0, _ := ret[0].(bool)
	return ret0
}

// isAdvanced indicates an expected call of isAdvanced.
func (mr *MockbaseMetricInterfaceMockRecorder) isAdvanced() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isAdvanced", reflect.TypeOf((*MockbaseMetricInterface)(nil).isAdvanced))
}

// isLocalContext mocks base method.
func (m *MockbaseMetricInterface) isLocalContext() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isLocalContext")
	ret0, _ := ret[0].(bool)
	return ret0
}

// isLocalContext indicates an expected call of isLocalContext.
func (mr *MockbaseMetricInterfaceMockRecorder) isLocalContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isLocalContext", reflect.TypeOf((*MockbaseMetricInterface)(nil).isLocalContext))
}

// sourceCtx mocks base method.
func (m *MockbaseMetricInterface) sourceCtx() ContextOptionsInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "sourceCtx")
	ret0, _ := ret[0].(ContextOptionsInterface)
	return ret0
}

// sourceCtx indicates an expected call of sourceCtx.
func (mr *MockbaseMetricInterfaceMockRecorder) sourceCtx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "sourceCtx", reflect.TypeOf((*MockbaseMetricInterface)(nil).sourceCtx))
}

// trackedMetricLabels mocks base method.
func (m *MockbaseMetricInterface) trackedMetricLabels() [][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "trackedMetricLabels")
	ret0, _ := ret[0].([][]string)
	return ret0
}

// trackedMetricLabels indicates an expected call of trackedMetricLabels.
func (mr *MockbaseMetricInterfaceMockRecorder) trackedMetricLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "trackedMetricLabels", reflect.TypeOf((*MockbaseMetricInterface)(nil).trackedMetricLabels))
}

// updated mocks base method.
func (m *MockbaseMetricInterface) updated(lbs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "updated", lbs)
}

// updated indicates an expected call of updated.
func (mr *MockbaseMetricInterfaceMockRecorder) updated(lbs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updated", reflect.TypeOf((*MockbaseMetricInterface)(nil).updated), lbs)
}
