// Code generated by MockGen. DO NOT EDIT.
// Source: types_linux.go
//
// Generated by this command:
//
//	mockgen -source=types_linux.go -destination=infiniband_mock_generated_linux.go -package=infiniband
//

// Package infiniband is a generated GoMock package.
package infiniband
