// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: pkg/utils/metadata.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSType int32

const (
	DNSType_UNKNOWN  DNSType = 0
	DNSType_QUERY    DNSType = 1
	DNSType_RESPONSE DNSType = 2
)

// Enum value maps for DNSType.
var (
	DNSType_name = map[int32]string{
		0: "UNKNOWN",
		1: "QUERY",
		2: "RESPONSE",
	}
	DNSType_value = map[string]int32{
		"UNKNOWN":  0,
		"QUERY":    1,
		"RESPONSE": 2,
	}
)

func (x DNSType) Enum() *DNSType {
	p := new(DNSType)
	*p = x
	return p
}

func (x DNSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNSType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_utils_metadata_proto_enumTypes[0].Descriptor()
}

func (DNSType) Type() protoreflect.EnumType {
	return &file_pkg_utils_metadata_proto_enumTypes[0]
}

func (x DNSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNSType.Descriptor instead.
func (DNSType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_utils_metadata_proto_rawDescGZIP(), []int{0}
}

type RetinaMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes uint64 `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// DNS metadata.
	DnsType      DNSType `protobuf:"varint,2,opt,name=dns_type,json=dnsType,proto3,enum=utils.DNSType" json:"dns_type,omitempty"`
	NumResponses uint32  `protobuf:"varint,3,opt,name=num_responses,json=numResponses,proto3" json:"num_responses,omitempty"`
	// TCP ID. Either Tsval or Tsecr will be set.
	TcpId uint64 `protobuf:"varint,4,opt,name=tcp_id,json=tcpId,proto3" json:"tcp_id,omitempty"`
}

func (x *RetinaMetadata) Reset() {
	*x = RetinaMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_utils_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetinaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetinaMetadata) ProtoMessage() {}

func (x *RetinaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_utils_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetinaMetadata.ProtoReflect.Descriptor instead.
func (*RetinaMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_utils_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *RetinaMetadata) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *RetinaMetadata) GetDnsType() DNSType {
	if x != nil {
		return x.DnsType
	}
	return DNSType_UNKNOWN
}

func (x *RetinaMetadata) GetNumResponses() uint32 {
	if x != nil {
		return x.NumResponses
	}
	return 0
}

func (x *RetinaMetadata) GetTcpId() uint64 {
	if x != nil {
		return x.TcpId
	}
	return 0
}

var File_pkg_utils_metadata_proto protoreflect.FileDescriptor

var file_pkg_utils_metadata_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x69, 0x6e, 0x61, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x64, 0x6e,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x75,
	0x74, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x4e, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x64, 0x6e,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6e, 0x75,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x63,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x63, 0x70, 0x49,
	0x64, 0x2a, 0x2f, 0x0a, 0x07, 0x44, 0x4e, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45,
	0x52, 0x59, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45,
	0x10, 0x02, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x6b, 0x61, 0x70, 0x70, 0x69, 0x65, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_utils_metadata_proto_rawDescOnce sync.Once
	file_pkg_utils_metadata_proto_rawDescData = file_pkg_utils_metadata_proto_rawDesc
)

func file_pkg_utils_metadata_proto_rawDescGZIP() []byte {
	file_pkg_utils_metadata_proto_rawDescOnce.Do(func() {
		file_pkg_utils_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_utils_metadata_proto_rawDescData)
	})
	return file_pkg_utils_metadata_proto_rawDescData
}

var file_pkg_utils_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_utils_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_utils_metadata_proto_goTypes = []interface{}{
	(DNSType)(0),           // 0: utils.DNSType
	(*RetinaMetadata)(nil), // 1: utils.RetinaMetadata
}
var file_pkg_utils_metadata_proto_depIdxs = []int32{
	0, // 0: utils.RetinaMetadata.dns_type:type_name -> utils.DNSType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_utils_metadata_proto_init() }
func file_pkg_utils_metadata_proto_init() {
	if File_pkg_utils_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_utils_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetinaMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_utils_metadata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_utils_metadata_proto_goTypes,
		DependencyIndexes: file_pkg_utils_metadata_proto_depIdxs,
		EnumInfos:         file_pkg_utils_metadata_proto_enumTypes,
		MessageInfos:      file_pkg_utils_metadata_proto_msgTypes,
	}.Build()
	File_pkg_utils_metadata_proto = out.File
	file_pkg_utils_metadata_proto_rawDesc = nil
	file_pkg_utils_metadata_proto_goTypes = nil
	file_pkg_utils_metadata_proto_depIdxs = nil
}
