apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority-data: <ca>
    <server>
contexts:
- name: azure-retina-windows@kubernetes
  context:
    cluster: kubernetes
    namespace: {{ .Values.namespace }}
    user: azure-retina-windows
current-context: azure-retina-windows@kubernetes
users:
- name: azure-retina-windows
  user:
    token: <token>
