{{- if .Values.agent.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retina-cluster-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: retina-agent
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: retina-cluster-reader
  apiGroup: rbac.authorization.k8s.io

{{- end}}