{{- if and .Values.agent.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

{{- end }}
