apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapinger-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
