apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    app: kapinger
spec:
  selector:
    app: kapinger
    unique-dep-label: "{{.Index}}"
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
