apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "retina.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    k8s-app: {{ include "retina.name" . }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
