{
 "title": "Kubernetes / Networking / Retina (Hubble) / DNS",
 "tags": [
  "k8s:retina-network-observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(up{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNS Requests",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes) > 0",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes) > 0",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Missing Response",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    1 - (\r\n        sum (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}) by (qtypes) / sum (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}) by (qtypes)\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes)\r\n    ) > bool 0\r\n) > 0",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Response IPs Returned",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode=\"No Error\"}[$__rate_interval])) by (ips_returned) > 0",
     "legendFormat": "{{ips_returned}}"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    label_replace(\r\n        sum by (rcode, qtypes) (\r\n            rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"NoError\"}[$__rate_interval])\r\n        ) > 0, \"rcode\", \"non-existent domain\", \"rcode\", \"nxdomain\"\r\n    ), \"rcode\", \"server failure\", \"rcode\", \"servfail\"\r\n)",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Requests)",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "round(topk(10, sum (60*rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (query, qtypes)), 1)",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Responses)",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "resp/min" } },
   "targets": [
    {
     "expr": "round(topk(10, sum (60*rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (query, qtypes)), 1)",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "DNS Response Table",
   "type": "table",
   "description": "Non-Cilium only",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  label_replace(\r\n      sum by (query, qtypes, response, rcode) (\r\n        60*rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])\r\n      ), \"rcode\", \"non-existent domain\", \"rcode\", \"nxdomain\"\r\n  ), \"rcode\", \"success\", \"rcode\", \"noerror\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Pods with DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"No Error\", destination=~\".*/.*\"}[1m])) by (destination)",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}