issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  new-from-rev: origin/main
  exclude-rules:
    # some type names are caps/underscore to map OS primitive types
    - path: pkg/metrics/types_windows.go
      linters:
        - revive
        - mnd
        - var-naming
    - path: pkg/metrics/types_linux.go
      linters:
        - revive
        - mnd
        - var-naming
linters:
  presets: 
  - bugs
  - error
  - format
  - performance
  - unused
  disable:
  - gci
  enable:
  - exportloopref
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - mnd
  - goprintffuncname
  - gosimple
  - lll
  - misspell
  - nakedret
  - promlinter
  - revive
  - predeclared
linters-settings:
  gocritic:
    enabled-tags:
    - "diagnostic"
    - "style"
    - "performance"
    disabled-checks:
    - "hugeParam"
  lll:
    line-length: 200
