{{- if and (or .Values.hubble.enabled .Values.hubble.relay.standalone.enabled) .Values.hubble.relay.enabled .Values.hubble.relay.grpcRoute.enabled .Values.hubble.relay.backendTrafficPolicy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: hubble-relay
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: hubble-relay
{{- with .Values.hubble.relay.backendTrafficPolicy.spec }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
