{{- if and .Values.hubble.enabled .Values.hubble.relay.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
  {{- with .Values.hubble.relay.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    k8s-app: hubble-relay
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: retina
spec:
  type: {{ .Values.hubble.relay.service.type | quote }}
  {{- if and .Values.hubble.relay.service.trafficDistribution (semverCompare ">=1.31-0" .Capabilities.KubeVersion.GitVersion) }}
  trafficDistribution: {{ .Values.hubble.relay.service.trafficDistribution }}
  {{- end }}
  selector:
    k8s-app: hubble-relay
  ports:
  - protocol: TCP
  {{- if .Values.hubble.relay.servicePort }}
    port: {{ .Values.hubble.relay.servicePort }}
  {{- else }}
    port: {{ .Values.hubble.relay.tls.server.enabled | ternary 443 80 }}
  {{- end }}
    targetPort: {{ .Values.hubble.relay.listenPort }}
    {{- if and (eq "NodePort" .Values.hubble.relay.service.type) .Values.hubble.relay.service.nodePort }}
    nodePort: {{ .Values.hubble.relay.service.nodePort }}
    {{- end }}
{{- end }}
