apiServer:
  host: "0.0.0.0"
  port: 10093
logLevel: info
enableTelemetry: true
enabledPlugin: ["hnsstats"]
dataAggregationLevel: "high"
metricsInterval: "1s"
telemetryInterval: "15m"
enrichmentMode: "azure-vnet-statefile"
crictlCommandTimeout: "5s"
stateFileLocation: "/generic/file/location/azure-vnet.json"
