{{- if .Values.operator.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: retina-operator-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: retina-operator-rolebinding
  namespace: {{ .Values.operator.leaderElectionNamespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: retina-operator-role
subjects:
- kind: ServiceAccount
  name: retina-operator
  namespace: {{ .Values.Namespace }}

{{- end -}}
