{
 "title": "Kubernetes / Networking / Pod Traffic",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod Name ",
    "query": {
     "query": "query_result(retina_adv_forward_count)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(retina_adv_forward_count{source_podname=~\"$pod\"}[1m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(retina_adv_forward_count{destination_podname=~\"$pod\"}[1m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "All Outgoing pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(source_podname) (irate(retina_adv_forward_count{destination_podname!=\"unknown\", source_podname!=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Incoming pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(destination_podname) (irate(retina_adv_forward_count{destination_podname!=\"unknown\", source_podname!=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped pps per source pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(source_podname) (irate(retina_adv_drop_count{destination_podname!=\"unknown\", source_podname!=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped pps per Destination pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(destination_podname) (irate(retina_adv_forward_count{destination_podname!=\"unknown\", source_podname!=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Outgoing pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(source_ip) (irate(retina_adv_forward_count{source_podname=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Incoming pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(destination_ip) (irate(retina_adv_forward_count{destination_podname=\"unknown\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods Outgoing traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by(source_podname) (irate(retina_adv_forward_count{source_podname!=\"unknown\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods Incoming traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "topk(10, sum by(destination_podname) (irate(retina_adv_forward_count{destination_podname!=\"unknown\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API server latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg by(instance) (sum by(le, instance) (rate(retina_node_apiserver_handshake_latency_ms_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}