// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dropreason

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type kprobeDropReasonT uint32

type kprobeMapKey struct {
	Prefixlen uint32
	Data      uint32
}

type kprobeMetricsMapKey struct {
	DropType  uint32
	ReturnVal uint32
}

type kprobeMetricsMapValue struct {
	Count uint64
	Bytes uint64
}

type kprobePacket struct {
	SrcIp       uint32
	DstIp       uint32
	SrcPort     uint16
	DstPort     uint16
	Proto       uint8
	_           [3]byte
	SkbLen      uint64
	Direction   uint32
	Key         kprobeMetricsMapKey
	_           [4]byte
	Ts          uint64
	InFiltermap bool
	_           [7]byte
}

// loadKprobe returns the embedded CollectionSpec for kprobe.
func loadKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kprobe: %w", err)
	}

	return spec, err
}

// loadKprobeObjects loads kprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kprobeObjects
//	*kprobePrograms
//	*kprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeSpecs struct {
	kprobeProgramSpecs
	kprobeMapSpecs
}

// kprobeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeProgramSpecs struct {
	InetCskAccept         *ebpf.ProgramSpec `ebpf:"inet_csk_accept"`
	InetCskAcceptRet      *ebpf.ProgramSpec `ebpf:"inet_csk_accept_ret"`
	KfreeSkbReason        *ebpf.ProgramSpec `ebpf:"kfree_skb_reason"`
	NfConntrackConfirm    *ebpf.ProgramSpec `ebpf:"nf_conntrack_confirm"`
	NfConntrackConfirmRet *ebpf.ProgramSpec `ebpf:"nf_conntrack_confirm_ret"`
	NfHookSlow            *ebpf.ProgramSpec `ebpf:"nf_hook_slow"`
	NfHookSlowRet         *ebpf.ProgramSpec `ebpf:"nf_hook_slow_ret"`
	NfNatInetFn           *ebpf.ProgramSpec `ebpf:"nf_nat_inet_fn"`
	NfNatInetFnRet        *ebpf.ProgramSpec `ebpf:"nf_nat_inet_fn_ret"`
	TcpV4ConnectRet       *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_ret"`
}

// kprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeMapSpecs struct {
	AcceptPids       *ebpf.MapSpec `ebpf:"accept_pids"`
	DropPids         *ebpf.MapSpec `ebpf:"drop_pids"`
	DropreasonEvents *ebpf.MapSpec `ebpf:"dropreason_events"`
	MetricsMap       *ebpf.MapSpec `ebpf:"metrics_map"`
	NatdropPids      *ebpf.MapSpec `ebpf:"natdrop_pids"`
	RetinaFilterMap  *ebpf.MapSpec `ebpf:"retina_filter_map"`
}

// kprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobeObjects struct {
	kprobePrograms
	kprobeMaps
}

func (o *kprobeObjects) Close() error {
	return _KprobeClose(
		&o.kprobePrograms,
		&o.kprobeMaps,
	)
}

// kprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobeMaps struct {
	AcceptPids       *ebpf.Map `ebpf:"accept_pids"`
	DropPids         *ebpf.Map `ebpf:"drop_pids"`
	DropreasonEvents *ebpf.Map `ebpf:"dropreason_events"`
	MetricsMap       *ebpf.Map `ebpf:"metrics_map"`
	NatdropPids      *ebpf.Map `ebpf:"natdrop_pids"`
	RetinaFilterMap  *ebpf.Map `ebpf:"retina_filter_map"`
}

func (m *kprobeMaps) Close() error {
	return _KprobeClose(
		m.AcceptPids,
		m.DropPids,
		m.DropreasonEvents,
		m.MetricsMap,
		m.NatdropPids,
		m.RetinaFilterMap,
	)
}

// kprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobePrograms struct {
	InetCskAccept         *ebpf.Program `ebpf:"inet_csk_accept"`
	InetCskAcceptRet      *ebpf.Program `ebpf:"inet_csk_accept_ret"`
	KfreeSkbReason        *ebpf.Program `ebpf:"kfree_skb_reason"`
	NfConntrackConfirm    *ebpf.Program `ebpf:"nf_conntrack_confirm"`
	NfConntrackConfirmRet *ebpf.Program `ebpf:"nf_conntrack_confirm_ret"`
	NfHookSlow            *ebpf.Program `ebpf:"nf_hook_slow"`
	NfHookSlowRet         *ebpf.Program `ebpf:"nf_hook_slow_ret"`
	NfNatInetFn           *ebpf.Program `ebpf:"nf_nat_inet_fn"`
	NfNatInetFnRet        *ebpf.Program `ebpf:"nf_nat_inet_fn_ret"`
	TcpV4ConnectRet       *ebpf.Program `ebpf:"tcp_v4_connect_ret"`
}

func (p *kprobePrograms) Close() error {
	return _KprobeClose(
		p.InetCskAccept,
		p.InetCskAcceptRet,
		p.KfreeSkbReason,
		p.NfConntrackConfirm,
		p.NfConntrackConfirmRet,
		p.NfHookSlow,
		p.NfHookSlowRet,
		p.NfNatInetFn,
		p.NfNatInetFnRet,
		p.TcpV4ConnectRet,
	)
}

func _KprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kprobe_bpfel_x86.o
var _KprobeBytes []byte
