FROM --platform=linux/amd64 mcr.microsoft.com/oss/go/microsoft/golang:1.21 AS builder

WORKDIR /app
COPY ./hack/tools .
ENV GOOS=windows
ENV GOARCH=amd64 

RUN echo "building kapinger for OS: $GOOS, ARCH: $GOARCH"
RUN go mod download

RUN CGO_ENABLED=0 go build -o app.exe ./kapinger

FROM  mcr.microsoft.com/windows/nanoserver:ltsc2022
WORKDIR /app
COPY --from=builder /app/app.exe .
CMD ["app.exe"]
