{
 "title": "Kubernetes / Networking / Clusters",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Retina Network Observability\n\nVisualize metrics for any Kubernetes cluster using [Retina](https://retina.sh/) (any cloud provider, any CNI, any OS). Cycle between all dashboards in the dropdown above."
   }
  },
  { "title": "Fleet View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current Traffic by Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(networkobservability_forward_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Forwarded by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(networkobservability_forward_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Dropped Traffic by Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(networkobservability_drop_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(networkobservability_drop_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped By Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(networkobservability_drop_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic (on $cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Max Egress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Min Egress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Max Egress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Min Egress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Max Ingress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Min Ingress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Max Ingress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Min Ingress Packets"
    }
   ]
  },
  {
   "title": "Egress Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Egress Bytes"
    }
   ]
  },
  {
   "title": "Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Egress Packets"
    }
   ]
  },
  {
   "title": "Ingress Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Ingress Bytes"
    }
   ]
  },
  {
   "title": "Ingress Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Ingress Packets"
    }
   ]
  },
  { "title": "Drops (on $cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Packets Dropped - Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Egress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Ingress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Unknown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"unknown\", instance=~\"$Nodes\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Unknown)"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Reason",
   "type": "timeseries",
   "description": "Linux only. Values:\n- iptable_rule_drop: packet dropped in iptables, e.g., because of a NetworkPolicy if using --network-policy=azure\n- iptable_nat_drop: packet dropped in iptables during NAT (Network Address Translation)\n- tcp_connect_basic: packet dropped by tcp connect\n- tcp_accept_basic: packet dropped by tcp accept\n- tcp_close_basic: packet dropped by tcp close\n- conntrack_add_drop: packet dropped while conntrack (connection tracking) was adding the connection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(networkobservability_drop_bytes{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Reason",
   "type": "timeseries",
   "description": "Values:\n- Linux:\n  - iptable_rule_drop: packet dropped in iptables, e.g., because of a NetworkPolicy if using --network-policy=azure\n  - iptable_nat_drop: packet dropped in iptables during NAT (Network Address Translation)\n  - tcp_connect_basic: packet dropped by tcp connect\n  - tcp_accept_basic: packet dropped by tcp accept\n  - tcp_close_basic: packet dropped by tcp close\n  - conntrack_add_drop: packet dropped while conntrack (connection tracking) was adding the connection\n  - rx_dropped: an interface dropped a received packet\n  - tx_dropped: an interface dropped a transmitted packet\n- Windows:\n  - aclrule: dropped by an ACL rule in VFP, e.g., because of a NetworkPolicy\n  - endpoint: dropped by an HNS Pod Endpoint ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(networkobservability_drop_count{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (\r\n  label_replace(\r\n    rate(networkobservability_interface_stats{statistic_name=\"rx_dropped\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]),\r\n    \"reason\",\r\n    \"$1\",\r\n    \"statistic_name\",\r\n    \"(.*)\"\r\n  )\r\n)\r\nor # cannot combine these interface_stats expressions into one using regex, since regex would capture anything with rx_dropped or tx_dropped in it\r\nsum by (reason) (\r\n  label_replace(\r\n    rate(networkobservability_interface_stats{statistic_name=\"tx_dropped\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]),\r\n    \"reason\",\r\n    \"$1\",\r\n    \"statistic_name\",\r\n    \"(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(networkobservability_drop_bytes{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(networkobservability_drop_count{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections (on $cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Active Connections by State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum by(state) (networkobservability_tcp_state{cluster=\"$cluster\", instance=~\"$Nodes\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Active Connections by Remote Addr",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum by(address) (networkobservability_tcp_connection_remote{cluster=\"$cluster\", instance=~\"$Nodes\", address!~\"127.0.0.1|0.0.0.0\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Connection Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"tcptimeouts\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP Timeouts"
      }
     ]
    },
    {
     "title": "TCP Connection Resets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 62 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"resetcount\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP Resets"
      }
     ]
    },
    {
     "title": "TCP Connection Reorders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 62 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"tcptsreorder\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP Reorders"
      }
     ]
    },
    {
     "title": "Windows TCP Packets",
     "type": "timeseries",
     "description": "Windows only",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP packets"
      }
     ]
    },
    {
     "title": "Windows TCP RST Packets",
     "type": "timeseries",
     "description": "Windows only",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{flag=\"rst\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP Reset Packets"
      }
     ]
    },
    {
     "title": "Windows TCP SYN-ACK Packets",
     "type": "timeseries",
     "description": "Windows only",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{flag=\"synack\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "TCP SYN-ACK packets"
      }
     ]
    },
    {
     "title": "UDP Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(networkobservability_udp_connection_stats{statistic_name=\"active\", cluster=\"$cluster\", instance=~\"$Nodes\"})",
       "legendFormat": "Total UDP Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces/Nodes (on $cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Packets by Interface",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface_name) (rate(networkobservability_interface_stats{statistic_name=\"rx_packets\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "TX Packets by Interface",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface_name) (rate(networkobservability_interface_stats{statistic_name=\"tx_packets\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "Rx Cache Full error",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=~\"rx[0-9]+_cache_full\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tx No Op Errors",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=~\"tx[0-9]+_nop\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Dropped Rx Packets",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"rx_dropped\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Dropped Tx Packets",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"tx_dropped\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rx Comp Full Errors",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"rx_comp_full\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tx Send Full Errors",
     "type": "timeseries",
     "description": "Linux only",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"tx_send_full\", cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}