{
 "title": "Infiniband",
 "description": "Retina infiniband metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ibdev", "label": "Inifiniband Device Name", "query": "mlx5_1" }
  ]
 },
 "panels": [
  {
   "title": "Infiniband Metadata",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_infiniband_info{device=\"$ibdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical/Link State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_infiniband_physical_state_id{device=\"$ibdev\"}",
     "legendFormat": "PHY {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_state_id{device=\"$ibdev\"}",
     "legendFormat": "LINK {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Congestion Drops/Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_infiniband_port_discards_transmitted_total{device=\"$ibdev\"}",
     "legendFormat": "Port Discard {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_vl15_dropped_total{device=\"$ibdev\"}",
     "legendFormat": "VL15 Drops {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_port_constraint_errors_received_total{device=\"$ibdev\"}",
     "legendFormat": "Port Constrain RX {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_port_constraint_errors_transmitted_total{device=\"$ibdev\"}",
     "legendFormat": "Port Constrain TX {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "RX/TX Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_infiniband_port_data_transmitted_bytes_total{device=\"$ibdev\"}",
     "legendFormat": "TX {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_port_data_received_bytes_total{device=\"$ibdev\"}",
     "legendFormat": "RX {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "RX/TX Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_infiniband_port_packets_received_total{device=\"$ibdev\"}",
     "legendFormat": "RX {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_port_packets_transmitted_total{device=\"$ibdev\"}",
     "legendFormat": "TX {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_unicast_packets_received_total{device=\"$ibdev\"}",
     "legendFormat": "RX UNI {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_unicast_packets_transmitted_total{device=\"$ibdev\"}",
     "legendFormat": "TX UNI {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_multicast_packets_received_total{device=\"$ibdev\"}",
     "legendFormat": "RX MULTI {{instance}} {{device}}"
    },
    {
     "expr": "node_infiniband_multicast_packets_transmitted_total{device=\"$ibdev\"}",
     "legendFormat": "TX MULTI {{instance}} {{device}}"
    }
   ]
  }
 ]
}