// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package packetparsertcx

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type packetparsertcxCtEntry struct {
	EvictionTime                    uint32
	LastReportTxDir                 uint32
	LastReportRxDir                 uint32
	BytesSeenSinceLastReportTxDir   uint32
	BytesSeenSinceLastReportRxDir   uint32
	PacketsSeenSinceLastReportTxDir uint32
	PacketsSeenSinceLastReportRxDir uint32
	FlagsSeenSinceLastReportTxDir   struct {
		Syn uint32
		Ack uint32
		Fin uint32
		Rst uint32
		Psh uint32
		Urg uint32
		Ece uint32
		Cwr uint32
		Ns  uint32
	}
	FlagsSeenSinceLastReportRxDir struct {
		Syn uint32
		Ack uint32
		Fin uint32
		Rst uint32
		Psh uint32
		Urg uint32
		Ece uint32
		Cwr uint32
		Ns  uint32
	}
	TrafficDirection   uint8
	FlagsSeenTxDir     uint8
	FlagsSeenRxDir     uint8
	IsDirectionUnknown bool
	ConntrackMetadata  struct {
		BytesTxCount   uint64
		BytesRxCount   uint64
		PacketsTxCount uint32
		PacketsRxCount uint32
	}
}

type packetparsertcxCtV4Key struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	_       [3]byte
}

type packetparsertcxMapKey struct {
	Prefixlen uint32
	Data      uint32
}

type packetparsertcxPacket struct {
	T_nsec      uint64
	Bytes       uint32
	SrcIp       uint32
	DstIp       uint32
	SrcPort     uint16
	DstPort     uint16
	TcpMetadata struct {
		Seq    uint32
		AckNum uint32
		Tsval  uint32
		Tsecr  uint32
	}
	ObservationPoint          uint8
	TrafficDirection          uint8
	Proto                     uint8
	_                         [1]byte
	Flags                     uint16
	IsReply                   bool
	_                         [1]byte
	PreviouslyObservedPackets uint32
	PreviouslyObservedBytes   uint32
	PreviouslyObservedFlags   struct {
		Syn uint32
		Ack uint32
		Fin uint32
		Rst uint32
		Psh uint32
		Urg uint32
		Ece uint32
		Cwr uint32
		Ns  uint32
	}
	_                 [4]byte
	ConntrackMetadata struct {
		BytesTxCount   uint64
		BytesRxCount   uint64
		PacketsTxCount uint32
		PacketsRxCount uint32
	}
}

// loadPacketparsertcx returns the embedded CollectionSpec for packetparsertcx.
func loadPacketparsertcx() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketparsertcxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load packetparsertcx: %w", err)
	}

	return spec, err
}

// loadPacketparsertcxObjects loads packetparsertcx and converts it into a struct.
func loadPacketparsertcxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPacketparsertcx()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

type packetparsertcxSpecs struct {
	packetparsertcxProgramSpecs
	packetparsertcxMapSpecs
}

type packetparsertcxProgramSpecs struct {
	EndpointEgressFilter  *ebpf.ProgramSpec `ebpf:"endpoint_egress_filter"`
	EndpointIngressFilter *ebpf.ProgramSpec `ebpf:"endpoint_ingress_filter"`
	HostEgressFilter      *ebpf.ProgramSpec `ebpf:"host_egress_filter"`
	HostIngressFilter     *ebpf.ProgramSpec `ebpf:"host_ingress_filter"`
}

type packetparsertcxMapSpecs struct {
	RetinaConntrack              *ebpf.MapSpec `ebpf:"retina_conntrack"`
	RetinaFilter                 *ebpf.MapSpec `ebpf:"retina_filter"`
	RetinaPacketparserTcxEvents *ebpf.MapSpec `ebpf:"retina_packetparser_tcx_events"`
}

type packetparsertcxObjects struct {
	packetparsertcxPrograms
	packetparsertcxMaps
}

func (o *packetparsertcxObjects) Close() error {
	return _PacketparsertcxClose(
		&o.packetparsertcxPrograms,
		&o.packetparsertcxMaps,
	)
}

type packetparsertcxMaps struct {
	RetinaConntrack              *ebpf.Map `ebpf:"retina_conntrack"`
	RetinaFilter                 *ebpf.Map `ebpf:"retina_filter"`
	RetinaPacketparserTcxEvents *ebpf.Map `ebpf:"retina_packetparser_tcx_events"`
}

func (m *packetparsertcxMaps) Close() error {
	return _PacketparsertcxClose(
		m.RetinaConntrack,
		m.RetinaFilter,
		m.RetinaPacketparserTcxEvents,
	)
}

type packetparsertcxPrograms struct {
	EndpointEgressFilter  *ebpf.Program `ebpf:"endpoint_egress_filter"`
	EndpointIngressFilter *ebpf.Program `ebpf:"endpoint_ingress_filter"`
	HostEgressFilter      *ebpf.Program `ebpf:"host_egress_filter"`
	HostIngressFilter     *ebpf.Program `ebpf:"host_ingress_filter"`
}

func (p *packetparsertcxPrograms) Close() error {
	return _PacketparsertcxClose(
		p.EndpointEgressFilter,
		p.EndpointIngressFilter,
		p.HostEgressFilter,
		p.HostIngressFilter,
	)
}

func _PacketparsertcxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packetparsertcx_bpfel_arm64.o
var _PacketparsertcxBytes []byte
