{{- if and .Values.hubble.enabled .Values.hubble.metrics.enabled .Values.hubble.metrics.serviceMonitor.enabled }}
{{- $legacyServiceMonitorNamespace := dig "serviceMonitor" "namespace" "" (.Values.prometheus | default dict) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble
  namespace: {{ .Values.hubble.metrics.serviceMonitor.namespace | default $legacyServiceMonitorNamespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: cilium
    {{- with .Values.hubble.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.hubble.metrics.serviceMonitor.annotations .Values.hubble.annotations }}
  annotations:
    {{- with .Values.hubble.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.hubble.metrics.serviceMonitor.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.hubble.metrics.serviceMonitor.selectorLabels | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: {{ .Values.hubble.metrics.serviceMonitor.port | quote }}
    interval: {{ .Values.hubble.metrics.serviceMonitor.interval | quote }}
    honorLabels: true
    path: /metrics
    {{- with .Values.hubble.metrics.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.hubble.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.hubble.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.hubble.metrics.serviceMonitor.jobLabel | quote }}
{{- end }}
{{- end }}
