// Code generated by bpf2go; DO NOT EDIT.
//go:build arm || arm64

package dns

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type dnsDnsEvent struct {
	Timestamp uint64
	SrcIp     uint32
	DstIp     uint32
	SrcIp6    [16]uint8
	DstIp6    [16]uint8
	SrcPort   uint16
	DstPort   uint16
	Id        uint16
	Qtype     uint16
	Af        uint8
	Proto     uint8
	PktType   uint8
	Qr        uint8
	Rcode     uint8
	Pad       uint8
	Ancount   uint16
	DnsOff    uint16
	DataLen   uint16
	_         [4]byte
}

type dnsQueryKey struct {
	Id      uint16
	SrcPort uint16
	SrcIp   uint32
}

// loadDns returns the embedded CollectionSpec for dns.
func loadDns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dns: %w", err)
	}

	return spec, err
}

// loadDnsObjects loads dns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsObjects
//	*dnsPrograms
//	*dnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsSpecs struct {
	dnsProgramSpecs
	dnsMapSpecs
}

// dnsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsProgramSpecs struct {
	RetinaDnsFilter *ebpf.ProgramSpec `ebpf:"retina_dns_filter"`
}

// dnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsMapSpecs struct {
	RetinaDnsEvents  *ebpf.MapSpec `ebpf:"retina_dns_events"`
	RetinaDnsLatency *ebpf.MapSpec `ebpf:"retina_dns_latency"`
	TmpDnsEvents     *ebpf.MapSpec `ebpf:"tmp_dns_events"`
}

// dnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsObjects struct {
	dnsPrograms
	dnsMaps
}

func (o *dnsObjects) Close() error {
	return _DnsClose(
		&o.dnsPrograms,
		&o.dnsMaps,
	)
}

// dnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsMaps struct {
	RetinaDnsEvents  *ebpf.Map `ebpf:"retina_dns_events"`
	RetinaDnsLatency *ebpf.Map `ebpf:"retina_dns_latency"`
	TmpDnsEvents     *ebpf.Map `ebpf:"tmp_dns_events"`
}

func (m *dnsMaps) Close() error {
	return _DnsClose(
		m.RetinaDnsEvents,
		m.RetinaDnsLatency,
		m.TmpDnsEvents,
	)
}

// dnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsPrograms struct {
	RetinaDnsFilter *ebpf.Program `ebpf:"retina_dns_filter"`
}

func (p *dnsPrograms) Close() error {
	return _DnsClose(
		p.RetinaDnsFilter,
	)
}

func _DnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dns_bpfel_arm64.o
var _DnsBytes []byte
