// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

package packetparser

import (
	"context"
	"strings"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/microsoft/retina/internal/ktime"
	"github.com/microsoft/retina/pkg/log"
	"github.com/microsoft/retina/pkg/metrics"
	plugincommon "github.com/microsoft/retina/pkg/plugin/common"
	"github.com/microsoft/retina/pkg/utils"
	"github.com/pkg/errors"
	"go.uber.org/zap"
)

const (
	conntrackGCFrequency = 15 * time.Second
	conntrackMapName     = "retina_conntrack"
)

// InitConntrackMap creates and pins the retina_conntrack BPF map. It must be
// called from the privileged init container: the agent container can load
// packetparser's BPF program but lacks permission to pin new maps, so the
// pin must already exist when packetparser.o is loaded.
func InitConntrackMap() error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return errors.Wrap(err, "failed to remove memlock limit")
	}

	spec, err := loadPacketparser() //nolint:typecheck // generated by bpf2go
	if err != nil {
		return errors.Wrap(err, "failed to load packetparser spec")
	}

	mapSpec, ok := spec.Maps[conntrackMapName]
	if !ok {
		return errors.Errorf("%s not found in packetparser spec", conntrackMapName)
	}

	m, err := ebpf.NewMapWithOptions(mapSpec, ebpf.MapOptions{PinPath: plugincommon.MapPath})
	if err != nil {
		return errors.Wrapf(err, "failed to create %s", conntrackMapName)
	}
	if err := m.Close(); err != nil {
		return errors.Wrapf(err, "failed to close %s handle", conntrackMapName)
	}
	return nil
}

// runConntrackGC walks the retina_conntrack map on a ticker, evicting expired
// entries and (optionally) emitting node-level conntrack metrics. It blocks
// until ctx is cancelled.
func runConntrackGC(ctx context.Context, l *log.ZapLogger, ctMap *ebpf.Map, metricsEnabled bool) {
	if ctMap == nil {
		l.Warn("conntrack map not available, skipping GC loop")
		return
	}

	ticker := time.NewTicker(conntrackGCFrequency)
	defer ticker.Stop()

	l.Info("Starting Conntrack GC loop")

	for {
		select {
		case <-ctx.Done():
			l.Info("Stopping conntrack GC loop")
			return
		case <-ticker.C:
			var (
				key          packetparserCtV4Key
				value        packetparserCtEntry
				keysToDelete []packetparserCtV4Key
			)

			var noOfCtEntries, entriesDeleted int
			var packetsCountTx, packetsCountRx, totConnections uint32
			var bytesCountTx, bytesCountRx uint64

			iter := ctMap.Iterate()
			for iter.Next(&key, &value) {
				noOfCtEntries++
				// Check if the connection is closing or has expired.
				if ktime.MonotonicOffset.Seconds()+float64(value.EvictionTime) < float64((time.Now().Unix())) {
					// Iterating a hash map from which keys are being deleted is not safe.
					// So, we store the keys to be deleted in a list and delete them after the iteration.
					keyCopy := key
					keysToDelete = append(keysToDelete, keyCopy)
				}

				srcIP := utils.Int2ip(key.SrcIp).To4()
				dstIP := utils.Int2ip(key.DstIp).To4()
				sourcePortShort := uint32(utils.HostToNetShort(key.SrcPort))
				destinationPortShort := uint32(utils.HostToNetShort(key.DstPort))

				if metricsEnabled {
					ctMeta := value.ConntrackMetadata
					totConnections++
					bytesCountTx += ctMeta.BytesTxCount
					bytesCountRx += ctMeta.BytesRxCount
					packetsCountTx += ctMeta.PacketsTxCount
					packetsCountRx += ctMeta.PacketsRxCount
				}

				l.Debug("conntrack entry",
					zap.String("src_ip", srcIP.String()),
					zap.Uint32("src_port", sourcePortShort),
					zap.String("dst_ip", dstIP.String()),
					zap.Uint32("dst_port", destinationPortShort),
					zap.String("proto", decodeProto(key.Proto)),
					zap.Uint32("eviction_time", value.EvictionTime),
					zap.Uint8("traffic_direction", value.TrafficDirection),
					zap.String("flags_seen_tx_dir", decodeFlags(value.FlagsSeenTxDir)),
					zap.String("flags_seen_rx_dir", decodeFlags(value.FlagsSeenRxDir)),
					zap.Uint32("last_reported_tx_dir", value.LastReportTxDir),
					zap.Uint32("last_reported_rx_dir", value.LastReportRxDir),
					zap.Bool("is_direction_unknown", value.IsDirectionUnknown),
				)
			}
			if err := iter.Err(); err != nil {
				l.Error("Iterate failed", zap.Error(err))
			}

			if metricsEnabled {
				metrics.ConntrackPacketsTx.WithLabelValues().Set(float64(packetsCountTx))
				metrics.ConntrackBytesTx.WithLabelValues().Set(float64(bytesCountTx))
				metrics.ConntrackPacketsRx.WithLabelValues().Set(float64(packetsCountRx))
				metrics.ConntrackBytesRx.WithLabelValues().Set(float64(bytesCountRx))
				metrics.ConntrackTotalConnections.WithLabelValues().Set(float64(totConnections))
			}

			for _, k := range keysToDelete {
				if err := ctMap.Delete(k); err != nil {
					// Should only happen in a high connection churn scenario.
					l.Debug("Delete failed", zap.Error(err))
				} else {
					entriesDeleted++
				}
			}
			l.Debug("conntrack GC completed", zap.Int("number_of_entries", noOfCtEntries), zap.Int("entries_deleted", entriesDeleted))
		}
	}
}

func decodeFlags(flags uint8) string {
	var descriptions []string
	if flags&TCPFlagFIN != 0 {
		descriptions = append(descriptions, "FIN")
	}
	if flags&TCPFlagSYN != 0 {
		descriptions = append(descriptions, "SYN")
	}
	if flags&TCPFlagRST != 0 {
		descriptions = append(descriptions, "RST")
	}
	if flags&TCPFlagPSH != 0 {
		descriptions = append(descriptions, "PSH")
	}
	if flags&TCPFlagACK != 0 {
		descriptions = append(descriptions, "ACK")
	}
	if flags&TCPFlagURG != 0 {
		descriptions = append(descriptions, "URG")
	}
	if flags&TCPFlagECE != 0 {
		descriptions = append(descriptions, "ECE")
	}
	if flags&TCPFlagCWR != 0 {
		descriptions = append(descriptions, "CWR")
	}
	if len(descriptions) == 0 {
		return "None"
	}
	return strings.Join(descriptions, ", ")
}

func decodeProto(proto uint8) string {
	switch proto {
	case 6: //nolint:gomnd // TCP
		return "TCP"
	case 17: //nolint:gomnd // UDP
		return "UDP"
	default:
		return "Not supported"
	}
}
