apiVersion: v1
kind: Service
metadata:
  name: {{ include "retina.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ include "retina.name" . }}
    {{- include "retina.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "retina.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: workload
