{
 "title": "Kubernetes / Networking / Retina (Hubble) / Pod Flows (Workload)",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(up, cluster)" },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": "label_values(up{cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(label_replace(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\"}, \"ns\", \"$1\", \"destination\", \"(.*)\") or label_replace(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\"}, \"ns\", \"$1\", \"source\", \"(.*)\"))"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Workload Snapshot ($workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods with Outgoing Traffic (past 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (source) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[10m])\r\n  ) >= 0.01\r\n)",
     "legendFormat": "Pods with Outgoing Traffic"
    }
   ]
  },
  {
   "title": "Max Outgoing Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Outgoing Traffic"
    }
   ]
  },
  {
   "title": "Min Outgoing Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Outgoing Traffic"
    }
   ]
  },
  {
   "title": "Pods with Incoming Traffic (past 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (destination) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[10m])\r\n  ) >= 0.01\r\n)",
     "legendFormat": "Pods with Incoming Traffic"
    }
   ]
  },
  {
   "title": "Max Incoming Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Incoming Traffic"
    }
   ]
  },
  {
   "title": "Min Incoming Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"FORWARDED\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Incoming Traffic"
    }
   ]
  },
  {
   "title": "Pods with Outgoing Drops (past 10 minutes)",
   "type": "stat",
   "description": "Drops seen on the VM of the source Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (\r\n  sum by (source) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[10m])\r\n  ) >= 0.01\r\n)",
     "legendFormat": "Pods with Outgoing Drops"
    }
   ]
  },
  {
   "title": "Max Outgoing Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{verdict=\"DROPPED\", cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Outgoing Drops"
    }
   ]
  },
  {
   "title": "Min Outgoing Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{verdict=\"DROPPED\", cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Outgoing Drops"
    }
   ]
  },
  {
   "title": "Pods with Incoming Drops (past 10 minutes)",
   "type": "stat",
   "description": "Drops seen on the VM of the destination Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (\r\n  sum by (destination) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[10m])\r\n  ) >= 0.01\r\n)",
     "legendFormat": "Pods with Incoming Drops"
    }
   ]
  },
  {
   "title": "Max Incoming Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{verdict=\"DROPPED\", cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Incoming Drops"
    }
   ]
  },
  {
   "title": "Min Incoming Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_flows_processed_total{verdict=\"DROPPED\", cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Incoming Drops"
    }
   ]
  },
  { "title": "Flows (for $workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Outgoing Traffic by Trace Type",
   "type": "timeseries",
   "description": "Values:\n- to-stack: traffic leaving Pod\n- to-network/overlay: traffic leaving Node",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (type, subtype)",
     "legendFormat": "{{type}}/{{subtype}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic by Trace Type",
   "type": "timeseries",
   "description": "Values:\n- to-endpoint: traffic reaching Pod\n- from-network/overlay: traffic reaching Node",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (type, subtype)",
     "legendFormat": "{{type}}/{{subtype}}"
    }
   ]
  },
  {
   "title": "Outgoing Traffic by Verdict",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic by Verdict",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Heatmap of Outgoing Traffic for Top Source Pods",
   "type": "heatmap",
   "description": "TypeError means there are no drops or no data",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, round(sum by (source) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01)) > 0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Heatmap of Incoming Traffic for Top Destination Pods",
   "type": "heatmap",
   "description": "TypeError means there are no drops or no data",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, round(sum by (destination) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01)) > 0",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Stacked (Total) Outgoing Traffic by Source Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "round(sum by (source) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01) > 0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Stacked (Total) Incoming Traffic by Destination Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "round(sum by (destination) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01) > 0",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Drops (for $workload)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap of Outgoing Drops for Top Source Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (source) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Heatmap of Incoming Drops for Top Destination Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (destination) (\r\n  rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{destination}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Outgoing Drops by Source Pod",
     "type": "timeseries",
     "description": "Drops seen on the VM of the source Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(\r\n  sum by (source) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[$__rate_interval])\r\n  ), 0.01\r\n)",
       "legendFormat": "{{destination}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Incoming Drops by Destination Pod",
     "type": "timeseries",
     "description": "Drops seen on the VM of the destination Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(\r\n  sum by (destination) (\r\n    rate(hubble_flows_processed_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", verdict=\"DROPPED\"}[$__rate_interval])\r\n  ), 0.01\r\n)",
       "legendFormat": "{{destination}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP (for $workload)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Missing SYN-ACKs (past 10 minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (\r\n    (\r\n        (sum(\r\n            rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"SYN\"}[10m])\r\n        ) by (source) > 0) - sum(\r\n            label_replace(\r\n                sum(\r\n                    rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"SYN-ACK\"}[10m])\r\n                ) by (destination), \"source\", \"$1\", \"destination\", \"(.*)\"\r\n            )\r\n        ) without (destination)\r\n    ) >= 0.01\r\n)",
       "legendFormat": "Pods Missing SYN-ACKs"
      }
     ]
    },
    {
     "title": "Max Packets Missing SYN-ACKs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"SYN\"}[$__rate_interval])\r\n    ) by (source) > 0 - sum(\r\n        label_replace(\r\n            sum(\r\n                rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"SYN-ACK\"}[$__rate_interval])\r\n            ) by (destination), \"source\", \"$1\", \"destination\", \"(.*)\"\r\n        )\r\n    ) without (destination)\r\n), 0.01)",
       "legendFormat": "Max Packets Missing SYN-ACKs"
      }
     ]
    },
    {
     "title": "Min Packets Missing SYN-ACKs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"SYN\"}[$__rate_interval])\r\n    ) by (source) > 0 - sum(\r\n        label_replace(\r\n            sum(\r\n                rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"SYN-ACK\"}[$__rate_interval])\r\n            ) by (destination), \"source\", \"$1\", \"destination\", \"(.*)\"\r\n        )\r\n    ) without (destination)\r\n), 0.01) > 0",
       "legendFormat": "Min Packets Missing SYN-ACKs"
      }
     ]
    },
    {
     "title": "Heatmap of Missing TCP SYN-ACKs by Top Source Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "topk(10, round(\r\n  sum(\r\n      rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"SYN\"}[$__rate_interval])\r\n  ) by (source) > 0 - sum(\r\n      label_replace(\r\n          sum(\r\n              rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"SYN-ACK\"}[$__rate_interval])\r\n          ) by (destination), \"source\", \"$1\", \"destination\", \"(.*)\"\r\n      )\r\n  ) without (destination), 0.01\r\n)) > 0",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Missing TCP SYN-ACKs by Source Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"SYN\"}[$__rate_interval])\r\n    ) by (source) > 0 - sum(\r\n        label_replace(\r\n            sum(\r\n                rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"SYN-ACK\"}[$__rate_interval])\r\n            ) by (destination), \"source\", \"$1\", \"destination\", \"(.*)\"\r\n        )\r\n    ) without (destination), 0.01\r\n)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Pods with Outgoing RST (past 10 minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (\r\n    sum by (source) (\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"RST\"}[10m])\r\n    ) >= 0.01\r\n)",
       "legendFormat": "Pods with Outgoing RST"
      }
     ]
    },
    {
     "title": "Max Outgoing RST Packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Max Outgoing RST Packets"
      }
     ]
    },
    {
     "title": "Min Outgoing RST",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Min Outgoing RST Packets"
      }
     ]
    },
    {
     "title": "Pods with Incoming RST (past 10 minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (\r\n    sum by (destination) (\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"RST\"}[10m])\r\n    ) >= 0.01\r\n)",
       "legendFormat": "Pods with Incoming RST"
      }
     ]
    },
    {
     "title": "Max Incoming RST Packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Max Incoming RST Packets"
      }
     ]
    },
    {
     "title": "Min Incoming RST",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Min Incoming RST Packets"
      }
     ]
    },
    {
     "title": "Heatmap of Outgoing TCP RST by Top Source Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (source) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Heatmap of Incoming TCP RST by Top Destination Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (destination) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{destination}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Outgoing TCP RST by Source Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(sum by (source) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n), 0.01)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Incoming TCP RST by Destination Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(sum by (destination) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"RST\"}[$__rate_interval])\r\n), 0.01)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Pods with Outgoing FIN (past 10 minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (\r\n    sum by (source) (\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"FIN\"}[10m])\r\n    ) >= 0.01\r\n)",
       "legendFormat": "Pods with Outgoing FIN"
      }
     ]
    },
    {
     "title": "Max Outgoing FIN Packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Max Outgoing FIN Packets"
      }
     ]
    },
    {
     "title": "MIN Outgoing FIN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Min Outgoing FIN Packets"
      }
     ]
    },
    {
     "title": "Pods with Incoming FIN (past 10 minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (\r\n    sum by (destination) (\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"FIN\"}[10m])\r\n    ) >= 0.01\r\n)",
       "legendFormat": "Pods with Incoming FIN"
      }
     ]
    },
    {
     "title": "Max Incoming FIN Packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Max Incoming FIN Packets"
      }
     ]
    },
    {
     "title": "Min Incoming FIN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "round(sum (\r\n    sum(\r\n        rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n    )\r\n), 0.01)",
       "legendFormat": "Min Incoming FIN Packets"
      }
     ]
    },
    {
     "title": "Heatmap of Outgoing TCP FIN by Top Source Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (source) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Heatmap of Incoming TCP FIN by Top Destination Pods",
     "type": "heatmap",
     "description": "TypeError means there are no drops or no data",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "topk(10, round(sum by (destination) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n), 0.01)) > 0",
       "legendFormat": "{{destination}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Outgoing TCP FIN by Source Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(sum by (source) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n), 0.01)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Stacked (Total) Incoming TCP FIN by Destination Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "round(sum by (destination) (\r\n  rate(hubble_tcp_flags_total{cluster=~\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\", flag=\"FIN\"}[$__rate_interval])\r\n), 0.01)",
       "legendFormat": "{{source}}"
      }
     ]
    }
   ]
  }
 ]
}