// autogenerated
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by MockGen. DO NOT EDIT.
// Source: /home/enterprise/retina/pkg/plugin/linuxutil/types.go

// Package linuxutil is a generated GoMock package.
package linuxutil

import (
	reflect "reflect"

	netstat "github.com/cakturk/go-netstat/netstat"
	gomock "github.com/golang/mock/gomock"
)

// MockEthtoolInterface is a mock of EthtoolInterface interface.
type MockEthtoolInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEthtoolInterfaceMockRecorder
}

// MockEthtoolInterfaceMockRecorder is the mock recorder for MockEthtoolInterface.
type MockEthtoolInterfaceMockRecorder struct {
	mock *MockEthtoolInterface
}

// NewMockEthtoolInterface creates a new mock instance.
func NewMockEthtoolInterface(ctrl *gomock.Controller) *MockEthtoolInterface {
	mock := &MockEthtoolInterface{ctrl: ctrl}
	mock.recorder = &MockEthtoolInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthtoolInterface) EXPECT() *MockEthtoolInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEthtoolInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockEthtoolInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEthtoolInterface)(nil).Close))
}

// Stats mocks base method.
func (m *MockEthtoolInterface) Stats(intf string) (map[string]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", intf)
	ret0, _ := ret[0].(map[string]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockEthtoolInterfaceMockRecorder) Stats(intf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockEthtoolInterface)(nil).Stats), intf)
}

// MockNetstatInterface is a mock of NetstatInterface interface.
type MockNetstatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNetstatInterfaceMockRecorder
}

// MockNetstatInterfaceMockRecorder is the mock recorder for MockNetstatInterface.
type MockNetstatInterfaceMockRecorder struct {
	mock *MockNetstatInterface
}

// NewMockNetstatInterface creates a new mock instance.
func NewMockNetstatInterface(ctrl *gomock.Controller) *MockNetstatInterface {
	mock := &MockNetstatInterface{ctrl: ctrl}
	mock.recorder = &MockNetstatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetstatInterface) EXPECT() *MockNetstatInterfaceMockRecorder {
	return m.recorder
}

// TCPSocks mocks base method.
func (m *MockNetstatInterface) TCPSocks(accept netstat.AcceptFn) ([]netstat.SockTabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TCPSocks", accept)
	ret0, _ := ret[0].([]netstat.SockTabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TCPSocks indicates an expected call of TCPSocks.
func (mr *MockNetstatInterfaceMockRecorder) TCPSocks(accept interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TCPSocks", reflect.TypeOf((*MockNetstatInterface)(nil).TCPSocks), accept)
}

// UDPSocks mocks base method.
func (m *MockNetstatInterface) UDPSocks(accept netstat.AcceptFn) ([]netstat.SockTabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UDPSocks", accept)
	ret0, _ := ret[0].([]netstat.SockTabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UDPSocks indicates an expected call of UDPSocks.
func (mr *MockNetstatInterfaceMockRecorder) UDPSocks(accept interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UDPSocks", reflect.TypeOf((*MockNetstatInterface)(nil).UDPSocks), accept)
}
