apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  labels:
    app: kapinger
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      shared-N: N
      unique-dep-label: "{{.Index}}"
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: shared-{{???}}
