# Only applicable for windows images
ARG OS_VERSION=ltsc2022
# pinned base images

# mcr.microsoft.com/windows/servercore:ltsc2019 
FROM mcr.microsoft.com/windows/servercore@sha256:6fdf140282a2f809dae9b13fe441635867f0a27c33a438771673b8da8f3348a4 AS ltsc2019

# mcr.microsoft.com/windows/servercore:ltsc2022
FROM mcr.microsoft.com/windows/servercore@sha256:45952938708fbde6ec0b5b94de68bcdec3f8c838be018536b1e9e5bd95e6b943 AS ltsc2022

FROM ${OS_VERSION} AS agent-win
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows # default to windows
ARG OS_VERSION=ltsc2022
ARG REPO_PATH
ARG BINARIES_PATH
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
ENV OS_VERSION=${OS_VERSION}
ENV BINARIES_PATH=${BINARIES_PATH}
ENV REPO_PATH=${REPO_PATH}
COPY ${REPO_PATH}/retina/windows/kubeconfigtemplate.yaml kubeconfigtemplate.yaml
COPY ${REPO_PATH}/retina/windows/setkubeconfigpath.ps1 setkubeconfigpath.ps1
COPY ${BINARIES_PATH}/captureworkload.exe captureworkload.exe
COPY ${BINARIES_PATH}/controller.exe controller.exe
ADD https://github.com/microsoft/etl2pcapng/releases/download/v1.10.0/etl2pcapng.exe /etl2pcapng.exe
CMD ["controller.exe", "start", "--kubeconfig=.\\kubeconfig"]
