# Only applicable for Windows 2022.
# There is a discinction between Windows 2019 and other years.
# 2019 is built on a Linux host using buildx.
# 2022 is built on a Windows host using docker build without buildx.
# This is done to mitigate CVE-2013-3900 on Windows 2022.

ARG OS_VERSION=ltsc2022
ARG BUILDPLATFORM
# pinned base images

# skopeo inspect docker://mcr.microsoft.com/oss/go/microsoft/golang:1.24.11-1-windowsservercore-ltsc2022 --format "{{.Name}}@{{.Digest}}"
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/oss/go/microsoft/golang@sha256:55675a714b620fa84e103f71e4dcc430a6eda0bb511e26deaad96d1a72b16972 AS golang

# skopeo inspect docker://mcr.microsoft.com/windows/servercore:ltsc2022  --override-os windows --format "{{.Name}}@{{.Digest}}"
FROM mcr.microsoft.com/windows/servercore@sha256:3750d7fcd320130cc2ce61954902b71729e85ec2c07c5a2e83a6d6c7f34a61e5 AS ltsc2022

# build stages

# intermediate go generate stage
FROM golang AS intermediate 
ARG APP_INSIGHTS_ID # set to enable AI telemetry
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows # default to windows
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
COPY ./pkg/plugin /go/src/github.com/microsoft/retina/pkg/plugin
WORKDIR /go/src/github.com/microsoft/retina
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .

# capture binary
FROM intermediate AS capture-bin
ENV APP_INSIGHTS_ID=${APP_INSIGHTS_ID}
ENV VERSION=${VERSION}
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
RUN go build -v -o /go/bin/retina/captureworkload -ldflags '-X github.com/microsoft/retina/internal/buildinfo.Version="$env:VERSION" -X github.com/microsoft/retina/internal/buildinfo.ApplicationInsightsID="$env:APP_INSIGHTS_ID"' captureworkload/main.go

# controller binary
FROM intermediate AS controller-bin
ENV APP_INSIGHTS_ID=${APP_INSIGHTS_ID}
ENV VERSION=${VERSION}
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
RUN go build -x -v -o /go/bin/retina/controller -ldflags '-X github.com/microsoft/retina/internal/buildinfo.Version="$env:VERSION" -X github.com/microsoft/retina/internal/buildinfo.ApplicationInsightsID="$env:APP_INSIGHTS_ID"' controller/main.go 

# agent final image for windows 
FROM ${OS_VERSION} AS agent-win
# CVE-2013-3900 Mitigation
RUN reg add "HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Wintrust\Config" /v "EnableCertPaddingCheck" /t REG_DWORD /d "1" /f
RUN reg add "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config" /v "EnableCertPaddingCheck" /t REG_DWORD /d "1" /f
COPY --from=controller-bin /go/src/github.com/microsoft/retina/windows/kubeconfigtemplate.yaml kubeconfigtemplate.yaml
COPY --from=controller-bin /go/src/github.com/microsoft/retina/windows/setkubeconfigpath.ps1 setkubeconfigpath.ps1
COPY --from=controller-bin /go/bin/retina/controller controller.exe
COPY --from=capture-bin /go/bin/retina/captureworkload captureworkload.exe
ADD https://github.com/microsoft/etl2pcapng/releases/download/v1.10.0/etl2pcapng.exe /etl2pcapng.exe
CMD ["controller.exe", "start", "--kubeconfig=.\\kubeconfig"]
