# pinned base image
# skopeo inspect docker://mcr.microsoft.com/windows/servercore:ltsc2019  --override-os windows --format "{{.Name}}@{{.Digest}}"
FROM mcr.microsoft.com/windows/servercore@sha256:95e0ef9b57f0c1ab25dc6f66cf892ff48738136ccabe06e9a124b8ef96653250 AS ltsc2019

FROM ltsc2019 AS agent-win
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows # default to windows
ARG OS_VERSION=ltsc2019
ARG REPO_PATH
ARG BINARIES_PATH
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
ENV OS_VERSION=${OS_VERSION}
ENV BINARIES_PATH=${BINARIES_PATH}
ENV REPO_PATH=${REPO_PATH}
# CVE-2013-3900 Mitigation
RUN reg add "HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Wintrust\Config" /v "EnableCertPaddingCheck" /t REG_DWORD /d "1" /f
RUN reg add "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config" /v "EnableCertPaddingCheck" /t REG_DWORD /d "1" /f
COPY ${REPO_PATH}/windows/kubeconfigtemplate.yaml kubeconfigtemplate.yaml
COPY ${REPO_PATH}/windows/setkubeconfigpath.ps1 setkubeconfigpath.ps1
COPY ${BINARIES_PATH}/captureworkload.exe captureworkload.exe
COPY ${BINARIES_PATH}/controller.exe controller.exe
ADD https://github.com/microsoft/etl2pcapng/releases/download/v1.10.0/etl2pcapng.exe /etl2pcapng.exe
CMD ["controller.exe", "start", "--kubeconfig=.\\kubeconfig"]
