ARG builderImage="acnpublic.azurecr.io/retina-builder:0.0.1"
ARG toolsImage="acnpublic.azurecr.io/retina-tools:0.0.1"

# Stage: Builder
FROM ${builderImage} as builder

# ----------------------------------------------------------------------------------- #

# Stage: Tools
FROM ${toolsImage} as clang

# ----------------------------------------------------------------------------------- #

# Stage: Base distroless image
FROM mcr.microsoft.com/mirror/gcr/distroless/cc-debian11:latest@sha256:b53fbf5f81f4a120a489fedff2092e6fcbeacf7863fce3e45d99cc58dc230ccc as base

LABEL Name=retina-controller Version=0.0.1

# Copy dependencies for clang and tools.
COPY --from=clang /lib/ /lib
COPY --from=clang /usr/lib/ /usr/lib

# Copy clang+llvm.
COPY --from=clang /usr/local/clang+llvm/bin/clang /bin

# Copy tools.
COPY --from=clang /tmp/bin/ /bin

# Copy the Retina binary.
COPY --from=builder /go/bin/retina/controller /retina/controller
COPY --from=builder /go/bin/retina/captureworkload /retina/captureworkload

# Copy the plugin eBPF code and headers.
COPY --from=builder /go/src/github.com/microsoft/retina/pkg/plugin /go/src/github.com/microsoft/retina/pkg/plugin

EXPOSE 80
ENTRYPOINT ["./retina/controller"]
