# Only applicable for windows images
ARG OS_VERSION=ltsc2022
# pinned base images

# mcr.microsoft.com/windows/servercore:ltsc2019 
FROM mcr.microsoft.com/windows/servercore@sha256:1883d9fb02b90ec20783f9376e004e125b28c652a73d821416444aadde6600b0 AS ltsc2019

# mcr.microsoft.com/windows/servercore:ltsc2022
FROM mcr.microsoft.com/windows/servercore@sha256:d31ac6a9b0c435679f941677661dd2fc555620348198c506e78e9ba70352e406 AS ltsc2022

FROM ${OS_VERSION} AS agent-win
ARG GOARCH=amd64 # default to amd64
ARG GOOS=windows # default to windows
ARG OS_VERSION=ltsc2022
ARG REPO_PATH
ARG BINARIES_PATH
ENV GOARCH=${GOARCH}
ENV GOOS=${GOOS}
ENV OS_VERSION=${OS_VERSION}
ENV BINARIES_PATH=${BINARIES_PATH}
ENV REPO_PATH=${REPO_PATH}
COPY ${REPO_PATH}/retina/windows/kubeconfigtemplate.yaml kubeconfigtemplate.yaml
COPY ${REPO_PATH}/retina/windows/setkubeconfigpath.ps1 setkubeconfigpath.ps1
COPY ${BINARIES_PATH}/captureworkload.exe captureworkload.exe
COPY ${BINARIES_PATH}/controller.exe controller.exe
ADD https://github.com/microsoft/etl2pcapng/releases/download/v1.10.0/etl2pcapng.exe /etl2pcapng.exe
CMD ["controller.exe", "start", "--kubeconfig=.\\kubeconfig"]