# skopeo inspect docker://mcr.microsoft.com/oss/go/microsoft/golang:1.26.2-azurelinux3.0 --format "{{.Name}}@{{.Digest}}"
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/oss/go/microsoft/golang:1.26.2-azurelinux3.0@sha256:ee3b11755cb3401848dc3140bbaae8da81dce6f7c7569857b2f45f040ae8868b

LABEL Name=retina-builder Version=0.0.1

RUN tdnf install -y unzip

WORKDIR /tmp

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v24.2/protoc-24.2-linux-x86_64.zip
RUN unzip protoc-24.2-linux-x86_64.zip -d protoc
RUN mv protoc/bin/protoc /usr/bin/protoc

WORKDIR /app
ENTRYPOINT /bin/sh -c "protoc -I=. --go_out=paths=source_relative:. ./pkg/utils/metadata_linux.proto && \
	protoc -I=. --go_out=paths=source_relative:. ./pkg/utils/metadata_darwin.proto && \
	protoc -I=. --go_out=paths=source_relative:. ./pkg/utils/metadata_windows.proto"
