FROM mcr.microsoft.com/oss/go/microsoft/golang:1.22 AS integration
LABEL Name=retina-integration Version=0.0.1

RUN apt-get update &&\
    apt-get -y install lsb-release wget software-properties-common gnupg file git make ca-certificates curl vim

RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get install -y kubectl sudo

COPY . /go/src/github.com/microsoft/retina
WORKDIR /go/src/github.com/microsoft/retina
RUN curl -LO https://github.com/kvaps/kubectl-node-shell/raw/master/kubectl-node_shell && \
    chmod +x ./kubectl-node_shell && \
    mv ./kubectl-node_shell /usr/local/bin/kubectl-node_shell

ENV BUILD_LOCALLY=true
RUN make install-kubectl-retina

ENTRYPOINT [ "make", "retina-integration" ]
