name: Daily Scale Test

on:
  push:
    branches:
      - alexcastilio/scale-test-workflow
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  call-scale-test:
    uses: ./.github/workflows/scale-test.yaml
    with: 
      num_deployments: 1000
      num_replicas: 20
      num_netpol: 0
      num_nodes: 1000
      # TODO: Change to true after checking cluster
      cleanup: false
    secrets: inherit
