name: E2E

on:
  schedule:
    - cron: '17 */2 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  perf_test:
    name: Retina Performance Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go version

      - name: Az CLI login
        uses: azure/login@v2
        if: ${{ github.event_name == 'merge_group' }}
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Run performance measurement for Retina
        env:
          AZURE_APP_INSIGHTS_KEY: ${{ secrets.AZURE_APP_INSIGHTS_KEY }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        shell: bash
        run: |
          set -euo pipefail
          go test -v ./test/e2e/*perf*.go -timeout 30m -tags=e2e -count=1  -args -image-tag=$(make version) -image-registry=${{vars.ACR_NAME}} -image-namespace=${{github.repository}}
