name: Test Multicloud

on:
  pull_request:
    paths:
      - 'test/multicloud/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  multicloud-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2.0.1
      with:
        tofu_version: 1.8.3

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: go mod download
      working-directory: test/multicloud/

    - name: Run tests
      run: make test
      working-directory: test/multicloud/
