name: Test Multicloud

on:
  pull_request:
    paths:
      - 'test/multicloud/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  multicloud-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
      with:
        tofu_version: 1.8.3

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: go mod download
      working-directory: test/multicloud/

    - name: Run tests
      run: make test
      working-directory: test/multicloud/
