// Package ebpfwindows is a Retina plugin for Windows that sources network
// telemetry from the eBPF-for-Windows data plane (the WCN / Cilium-on-Windows
// observability API) instead of the legacy HNS/VFP (hnsstats) path.
//
// Design: the plugin implements the Retina registry.Plugin contract and
// delegates event production to an EventSource. The source is an interface so
// it can be backed by a real WCN/eBPF reader in production and by a synthetic
// harness in unit tests. This keeps the plugin testable without a Windows
// cluster.
//
// Data flow:
//
//	EventSource.Start(ctx) -> (<-chan *v1.Event, error)
//	  -> run loop: enricher.Write(ev)
//	  -> forward ev to the external channel (drop when full, count lost)
package ebpfwindows

import (
	"context"
	"sync"

	v1 "github.com/cilium/cilium/pkg/hubble/api/v1"
	"github.com/microsoft/retina/pkg/config"
	"github.com/microsoft/retina/pkg/enricher"
	"github.com/microsoft/retina/pkg/log"
	"github.com/microsoft/retina/pkg/metrics"
	"github.com/microsoft/retina/pkg/plugin/registry"
	"github.com/microsoft/retina/pkg/utils"
	"go.uber.org/zap"
)

const name = "ebpfwindows"

func init() {
	// Self-register so pluginmanager can look it up by name via registry.Get.
	registry.Add(name, New)
}

// New is the registry.PluginFunc. It returns a plugin using the default
// production source; tests inject a synthetic source via newPlugin.
func New(cfg *config.Config) registry.Plugin {
	return newPlugin(cfg, newDefaultSource())
}

// newPlugin wires an explicit source (test injection point).
func newPlugin(cfg *config.Config, src EventSource) registry.Plugin {
	return &Plugin{
		l:   log.Logger().Named(name),
		src: src,
	}
}

// EventSource abstracts "produce flow events on this node". Implementations must
// be safe to Start once and Stop once and must close the returned channel when
// the context is cancelled so the plugin loop can unblock.
type EventSource interface {
	// Start connects to the data plane and returns a channel of events.
	Start(ctx context.Context) (<-chan *v1.Event, error)
	// Stop releases resources held by the source.
	Stop() error
}

// defaultSource is the production placeholder for a WCN/eBPF-for-Windows reader.
// Implementing this is the remaining integration work (see source.go).
type defaultSource struct{}

func newDefaultSource() EventSource { return &defaultSource{} }

func (s *defaultSource) Start(_ context.Context) (<-chan *v1.Event, error) {
	ch := make(chan *v1.Event)
	close(ch)
	return ch, nil
}

func (s *defaultSource) Stop() error { return nil }

// Plugin consumes events from a WCN/eBPF source and feeds them into Retina.
type Plugin struct {
	l        *log.ZapLogger
	src      EventSource
	enricher enricher.EnricherInterface
	out      chan *v1.Event

	mu      sync.Mutex
	started bool
	cancel  context.CancelFunc
	wg      sync.WaitGroup
}

// Name returns the plugin name registered in the allowed plugin list.
func (p *Plugin) Name() string { return name }

// Generate is a no-op: eBPF-for-Windows programs are provided by the OS/WCN
// data plane, not generated by Retina at build time.
func (p *Plugin) Generate(_ context.Context) error {
	p.l.Debug("ebpfwindows: Generate is a no-op")
	return nil
}

// Compile is a no-op for the same reason as Generate.
func (p *Plugin) Compile(_ context.Context) error {
	p.l.Debug("ebpfwindows: Compile is a no-op")
	return nil
}

// Init prepares plugin runtime state.
func (p *Plugin) Init() error {
	p.l.Debug("ebpfwindows: Init")
	return nil
}

// Start begins consumption. It is idempotent.
func (p *Plugin) Start(ctx context.Context) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.started {
		return nil
	}

	// Use the singleton enricher only if the caller has not injected one
	// (e.g. via newPlugin in tests). This preserves test injection.
	if p.enricher == nil {
		p.enricher = enricher.Instance()
	}
	ctx, cancel := context.WithCancel(ctx)
	p.cancel = cancel
	p.started = true

	p.wg.Add(1)
	go func() {
		defer p.wg.Done()
		if err := p.run(ctx); err != nil {
			p.l.Error("ebpf-windows source loop exited", zap.Error(err))
		}
	}()
	return nil
}

// SetupChannel wires the downstream channel that receives the emitted flows.
func (p *Plugin) SetupChannel(ch chan *v1.Event) error {
	p.out = ch
	return nil
}

// Stop tears down consumption. It is idempotent.
func (p *Plugin) Stop() error {
	p.mu.Lock()
	if p.cancel != nil {
		p.cancel()
	}
	p.started = false
	p.mu.Unlock()

	p.wg.Wait()
	if p.src != nil {
		_ = p.src.Stop()
	}
	return nil
}

// run drives the source loop until the context is done.
func (p *Plugin) run(ctx context.Context) error {
	ch, err := p.src.Start(ctx)
	if err != nil {
		return err
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case ev, ok := <-ch:
			if !ok {
				return nil
			}
			if ev == nil {
				continue
			}

			if p.enricher != nil {
				p.enricher.Write(ev)
			}
			if p.out != nil {
				select {
				case p.out <- ev:
				default:
					metrics.LostEventsCounter.WithLabelValues(utils.ExternalChannel, name).Inc()
				}
			}
		}
	}
}
